replicaCount: 1

fullnameOverride: penny-auction-ui

image:
  repository: javatechnologies/penny-auction-ui
  tag: 0.1.4
resources:
  requests:
    memory: 64Mi
  limits:
    memory: 128Mi
port: 8080

service:
  type: NodePort
  port: 8080

